/**
 * Creates (or replaces) a single test article: slug `test-article`.
 * Uses your first author & category if present; otherwise creates minimal test docs.
 *
 * Run: npm run create-test-article
 * Requires: NEXT_PUBLIC_SANITY_PROJECT_ID, SANITY_API_WRITE_TOKEN in .env.local
 */
import { createClient } from "@sanity/client";
import { config as loadEnv } from "dotenv";

loadEnv({ path: ".env.local" });
loadEnv();

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID;
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || "production";
const token = process.env.SANITY_API_WRITE_TOKEN;

if (!projectId || !token) {
  console.error("Missing NEXT_PUBLIC_SANITY_PROJECT_ID or SANITY_API_WRITE_TOKEN in .env.local");
  process.exit(1);
}

const client = createClient({
  projectId,
  dataset,
  apiVersion: "2024-01-01",
  token,
  useCdn: false,
});

const key = () => crypto.randomUUID();

async function uploadImage(url: string, filename: string) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch image: ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  return client.assets.upload("image", buf, { filename });
}

function p(text: string) {
  return {
    _type: "block" as const,
    _key: key(),
    style: "normal" as const,
    markDefs: [] as const,
    children: [{ _type: "span" as const, _key: key(), marks: [] as const, text }],
  };
}

function h2(text: string) {
  return {
    _type: "block" as const,
    _key: key(),
    style: "h2" as const,
    markDefs: [] as const,
    children: [{ _type: "span" as const, _key: key(), marks: [] as const, text }],
  };
}

async function main() {
  const hero = await uploadImage(
    "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=80",
    "test-article-hero.jpg",
  );

  let authorRef =
    (await client.fetch<string | null>(`*[_type == "author"] | order(_createdAt asc) [0]._id`)) ?? null;
  if (!authorRef) {
    authorRef = "author-test-autogen";
    await client.createOrReplace({
      _id: authorRef,
      _type: "author",
      name: "Test Author",
      slug: { current: "test-author" },
      role: "Autogenerated",
      bio: "Created by npm run create-test-article so you have an author to attach posts to.",
      photo: {
        _type: "image",
        asset: { _type: "reference", _ref: hero._id },
        alt: "Placeholder portrait for test author",
      },
    });
    console.log("Created minimal author:", authorRef);
  }

  let categoryRef =
    (await client.fetch<string | null>(`*[_type == "category"] | order(_createdAt asc) [0]._id`)) ?? null;
  if (!categoryRef) {
    categoryRef = "category-test-autogen";
    await client.createOrReplace({
      _id: categoryRef,
      _type: "category",
      title: "Test",
      slug: { current: "test" },
      description: "Autogenerated category for test articles.",
    });
    console.log("Created minimal category:", categoryRef);
  }

  const doc = {
    _id: "article-test-hello",
    _type: "article",
    title: "Test article",
    slug: { current: "test-article" },
    excerpt:
      "A short placeholder post created from the repo script. Delete or unpublish it anytime from /studio.",
    featuredImage: {
      _type: "image",
      asset: { _type: "reference", _ref: hero._id },
      alt: "Laptop and notebook on a desk",
    },
    author: { _type: "reference", _ref: authorRef },
    categories: [{ _type: "reference", _ref: categoryRef }],
    tags: ["test", "internal"],
    publishedAt: new Date().toISOString(),
    body: [
      h2("Hello from the test article"),
      p(
        "If you can read this on the site, Sanity writes and Next.js reads are wired correctly. Open /studio to edit this document or remove it.",
      ),
      p("Try changing the title or adding a FAQ block to see JSON-LD update on the article page."),
    ],
    seoTitle: "Test article — Poland Nomad",
    seoDescription: "Placeholder article created via npm run create-test-article for local CMS checks.",
    keywords: ["test"],
    faqs: [
      {
        _type: "faqItem",
        _key: key(),
        question: "Is this article real content?",
        answer: "No. It is a smoke-test document you can replace with your own draft.",
      },
    ],
  };

  await client.createOrReplace(doc as never);
  console.log("Done. Open: /blog/test-article");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
